server:
  port: 3001 #服务提供者

#指定当前eureka客户端的注册地址
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:11111/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: easy-calc
